[package]
name = "wasm-everything"
version = "0.1.0"
authors = ["lightsing <light.tsing@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
wasmer = "1.0"

[workspace]
members = [
    "rt-interface",
    "examples/hello"
]