[package]
name = "hello"
version = "0.1.0"
authors = ["lightsing <light.tsing@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
wee_alloc = "0.4"
cstr = "0.2"
rt-interface = { path = "../../rt-interface" }
serde = { version = "1.0", features = ["derive"] }